# POST http://localhost:3003/api/blogs
# content-type: application/json

# {
#     "title": "Delete Post5",
#     "author": "Delete Mi5",
#     "url": "delete5.com",
#     "likes": 5
# }
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjQxOXRlc3QyIiwiaWQiOiI2NjEwMWNjNzQzYWU1Y2RiNzE0NGFkYzkiLCJpYXQiOjE3MTIzMzUzNTYsImV4cCI6MTcxMjMzODk1Nn0.2WbwMDe0R9r4mXmQGGm0TJ1xzKvWjuCAAq8G9TEPqT4

{
    "title": "create new post 4.22 test everything works!!",
    "author": "4.22",
    "url": "422.com",
    "likes": 422
}
