# POST http://localhost:3003/api/blogs
# content-type: application/json

# {
#     "title": "Delete Post5",
#     "author": "Delete Mi5",
#     "url": "delete5.com",
#     "likes": 5
# }
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjQxOXRlc3QyIiwiaWQiOiI2NjEwMWNjNzQzYWU1Y2RiNzE0NGFkYzkiLCJpYXQiOjE3MTIzMzE5ODcsImV4cCI6MTcxMjMzNTU4N30.qD-qS0ztWTC7E-4nOGmZ4DvleuPhhohRHWvyG7SQHNQ

{
    "title": "create new post 4.20",
    "author": "4.20",
    "url": "420.com",
    "likes": 420
}
