DELETE http://localhost:3003/api/blogs/66102a30bd3dfe4387abea1f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjQxOXRlc3QyIiwiaWQiOiI2NjEwMWNjNzQzYWU1Y2RiNzE0NGFkYzkiLCJpYXQiOjE3MTIzMzUzNTYsImV4cCI6MTcxMjMzODk1Nn0.2WbwMDe0R9r4mXmQGGm0TJ1xzKvWjuCAAq8G9TEPqT4